
import { Career, Scholarship, UserProfile } from './types';

export const INITIAL_USER: UserProfile = {
  name: '',
  grade: 'Class 10',
  interests: [],
  completedQuiz: false,
  savedCareers: [],
  skillProgress: {
    Communication: 20,
    Creativity: 20,
    Coding: 20,
    Logic: 20,
    Leadership: 20,
    Collaboration: 20
  },
  achievements: []
};

const generateId = (prefix: string, index: number) => `${prefix}${index + 100}`;

// Data Structure: [Title, Industry, Description, Salary, Education, GrowthScore, Tags, Skills, Subjects, Tools, Personality, FamousPerson]
// Note: Salaries are in Indian Rupees (L = Lakhs per annum).

const CAREER_RAW_DATA = [
  // --- TECHNOLOGY (High Growth) ---
  ["Data Scientist", "Technology", "Analyze complex data to help Indian companies like Jio and Tata make decisions.", "₹8L - ₹25L", "B.Tech CS/Stats", 95, "STEM,High Pay", "Python,SQL,ML", "Math,Stats", "Jupyter,Tableau", "Investigative", "Mukesh Ambani"],
  ["Software Engineer", "Technology", "Build software for India's booming tech ecosystem.", "₹6L - ₹24L", "B.Tech CS", 94, "STEM,Coding", "Java,Python", "Math,CS", "VS Code,Git", "Investigative", "Narayan Murthy"],
  ["Full Stack Developer", "Technology", "Build web apps for startups and MNCs.", "₹5L - ₹18L", "B.Tech CS", 94, "STEM,High Demand", "React,Node.js", "CS,Math", "VS Code,AWS", "Investigative", "Bhavish Aggarwal"],
  ["AI Engineer", "Technology", "Develop AI models for healthcare and finance.", "₹10L - ₹35L", "B.Tech AI", 99, "STEM,Future", "Deep Learning,NLP", "Math,Stats", "PyTorch", "Investigative", "Andrew Ng"],
  ["Cybersecurity Analyst", "Technology", "Protect Indian banking and gov systems.", "₹6L - ₹20L", "B.Tech CS", 96, "STEM,Security", "Ethical Hacking", "CS,Math", "Wireshark", "Investigative", "Saket Modi"],
  ["Cloud Architect", "Technology", "Design cloud infrastructure for companies.", "₹12L - ₹40L", "B.Tech CS", 96, "STEM,High Pay", "AWS,Azure", "CS,Math", "Docker", "Investigative", "Satya Nadella"],
  ["Blockchain Developer", "Technology", "Build decentralized apps and crypto systems.", "₹8L - ₹30L", "B.Tech CS", 92, "STEM,Future", "Solidity,Smart Contracts", "Math,CS", "Ethereum", "Investigative", "Sandeep Nailwal"],
  ["UI/UX Designer", "Technology", "Design user-friendly apps and websites.", "₹5L - ₹18L", "B.Des/Certification", 90, "Creative,Tech", "Figma,User Research", "Art,Psychology", "Figma,Adobe XD", "Artistic", "Unknown"],
  ["DevOps Engineer", "Technology", "Manage code deployment and servers.", "₹7L - ₹25L", "B.Tech CS", 93, "STEM,Tech", "CI/CD,Linux", "CS", "Jenkins,Kubernetes", "Investigative", "Unknown"],
  ["Mobile App Developer", "Technology", "Create Android/iOS apps.", "₹5L - ₹20L", "B.Tech CS", 92, "STEM,Mobile", "Flutter,Swift", "CS,Logic", "Android Studio", "Investigative", "Unknown"],
  ["Prompt Engineer", "Technology", "Optimize AI model outputs.", "₹6L - ₹18L", "Any Degree + Skill", 95, "Tech,New", "LLM Logic,English", "English,Logic", "ChatGPT,Gemini", "Artistic", "Unknown"],
  ["Game Developer", "Technology", "Create video games for mobile/PC.", "₹5L - ₹20L", "B.Tech/Diploma", 91, "Tech,Creative", "Unity,Unreal", "Math,CS", "Unity", "Artistic", "Unknown"],
  ["QA Tester", "Technology", "Test software for bugs.", "₹3L - ₹10L", "B.Tech/BCA", 85, "Tech,Stable", "Manual Testing", "CS", "Selenium", "Conventional", "Unknown"],
  ["System Administrator", "Technology", "Manage company computer systems.", "₹4L - ₹12L", "B.Tech/BCA", 85, "Tech,Ops", "Linux,Windows", "CS", "Server", "Realistic", "Unknown"],
  ["Network Engineer", "Technology", "Setup and manage internet networks.", "₹4L - ₹15L", "CCNA/B.Tech", 88, "Tech,Hardware", "Networking", "Physics,CS", "Cisco Packet Tracer", "Realistic", "Unknown"],
  ["SEO Specialist", "Technology", "Rank websites on Google.", "₹3L - ₹10L", "Any Degree", 89, "Tech,Marketing", "SEO,Analytics", "English", "Google Analytics", "Investigative", "Unknown"],
  ["Database Administrator", "Technology", "Manage data storage and security.", "₹6L - ₹18L", "B.Tech/BCA", 87, "Tech,Data", "SQL,Oracle", "CS", "SQL Server", "Conventional", "Unknown"],
  ["Hardware Engineer", "Technology", "Design computer components.", "₹5L - ₹20L", "B.Tech Electronics", 86, "Tech,Hardware", "Circuit Design", "Physics,Math", "PCB Tool", "Investigative", "Unknown"],
  ["Ethical Hacker", "Technology", "Find security flaws legally.", "₹6L - ₹25L", "CEH Certification", 94, "Tech,Cool", "Penetration Testing", "CS", "Kali Linux", "Investigative", "Unknown"],
  ["IoT Engineer", "Technology", "Connect devices to internet.", "₹5L - ₹18L", "B.Tech Electronics", 91, "Tech,Future", "Sensors,Arduino", "Phy,CS", "Arduino", "Investigative", "Unknown"],
  ["Big Data Engineer", "Technology", "Process large datasets.", "₹8L - ₹28L", "B.Tech CS", 93, "Tech,Data", "Hadoop,Spark", "CS", "AWS", "Investigative", "Unknown"],
  ["AR/VR Developer", "Technology", "Create Virtual Reality apps.", "₹6L - ₹20L", "B.Tech/Design", 90, "Creative,Tech", "Unity,Unreal", "CS,Art", "VR Headset", "Artistic", "Unknown"],
  ["Technical Support", "Technology", "Help customers with tech issues.", "₹2.5L - ₹6L", "BCA/Diploma", 80, "Tech,Service", "Troubleshooting", "CS", "Remote Tool", "Social", "Unknown"],
  ["Computer Hardware Tech", "Technology", "Repair computers.", "₹2.5L - ₹5L", "Diploma/ITI", 78, "Tech,Repair", "Repair", "Phy", "Screwdriver", "Realistic", "Unknown"],
  ["SAP Consultant", "Technology", "Manage SAP ERP systems.", "₹6L - ₹20L", "B.Tech/MBA", 88, "Tech,Biz", "SAP Modules", "CS,Biz", "SAP", "Enterprising", "Unknown"],
  ["Robotics Programmer", "Technology", "Code for industrial robots.", "₹5L - ₹15L", "B.Tech/Diploma", 90, "Tech,Future", "C++,Python", "Math,Phy", "ROS", "Investigative", "Unknown"],
  ["GIS Specialist", "Technology", "Map data for geography.", "₹4L - ₹10L", "M.Sc Geoinformatics", 82, "Tech,Geo", "Mapping", "Geo,CS", "ArcGIS", "Investigative", "Unknown"],
  ["IT Project Manager", "Technology", "Lead software projects.", "₹10L - ₹30L", "MBA/PMP", 90, "Tech,Mgmt", "Agile,Scrum", "Biz", "Jira", "Enterprising", "Unknown"],
  ["Technical Writer", "Technology", "Write software manuals.", "₹4L - ₹12L", "BA English/B.Tech", 80, "Tech,Writing", "Documentation", "English,CS", "Word", "Artistic", "Unknown"],
  ["Instructional Designer", "Technology", "Create e-learning courses.", "₹5L - ₹15L", "B.Ed/MA", 85, "EdTech,Design", "Curriculum Dev", "Psychology", "Articulate", "Artistic", "Unknown"],

  // --- ENGINEERING (Core & Diploma) ---
  ["Civil Engineer", "Engineering", "Design India's bridges, metros, and highways.", "₹4L - ₹15L", "B.Tech Civil", 82, "STEM,Core", "AutoCAD,Struct", "Physics,Math", "AutoCAD", "Realistic", "E Sreedharan"],
  ["Mechanical Engineer", "Engineering", "Design machines and automotive parts.", "₹4L - ₹16L", "B.Tech Mech", 83, "STEM,Core", "CAD,Thermodynamics", "Physics,Math", "SolidWorks", "Realistic", "Unknown"],
  ["Electrical Engineer", "Engineering", "Design electrical grids and systems.", "₹4L - ₹18L", "B.Tech Electrical", 85, "STEM,Core", "Circuits,Power", "Physics,Math", "MATLAB", "Investigative", "Unknown"],
  ["Automobile Engineer", "Engineering", "Design next-gen EVs.", "₹5L - ₹18L", "B.Tech Auto", 84, "STEM,Cars", "Vehicle Dynamics", "Physics,Math", "CATIA", "Realistic", "Anand Mahindra"],
  ["Robotics Engineer", "Engineering", "Build automation for manufacturing.", "₹6L - ₹22L", "B.Tech Robotics", 94, "STEM,Future", "ROS,C++", "Physics,Math", "ROS,Arduino", "Investigative", "Unknown"],
  ["Aerospace Engineer", "Engineering", "Design aircraft and spacecraft for ISRO/DRDO.", "₹8L - ₹25L", "B.Tech Aerospace", 90, "STEM,Space", "Aerodynamics", "Physics,Math", "ANSYS", "Investigative", "APJ Abdul Kalam"],
  ["Chemical Engineer", "Engineering", "Process design for oil, gas, and pharma.", "₹5L - ₹18L", "B.Tech Chemical", 86, "STEM,Industrial", "Process Control", "Chemistry,Math", "Aspen", "Investigative", "Mukesh Ambani"],
  ["Petroleum Engineer", "Engineering", "Extract oil and gas (ONGC).", "₹8L - ₹30L", "B.Tech Petroleum", 85, "STEM,High Pay", "Drilling", "Physics,Geo", "Simulators", "Realistic", "Unknown"],
  ["Mining Engineer", "Engineering", "Plan and supervise mine operations.", "₹6L - ₹20L", "B.Tech Mining", 80, "STEM,Core", "Geology,Safety", "Physics,Geo", "Survey Equip", "Realistic", "Unknown"],
  ["Textile Engineer", "Engineering", "Design fabric and production processes.", "₹4L - ₹12L", "B.Tech Textile", 78, "STEM,Creative", "Fabric Tech", "Chem,Art", "Looms", "Realistic", "Unknown"],
  ["Junior Engineer (Civil)", "Engineering", "Supervise construction sites.", "₹3L - ₹8L", "Diploma Civil", 85, "Core,Site", "Site Sup", "Math,Phy", "Level", "Realistic", "Unknown"],
  ["Junior Engineer (Mech)", "Engineering", "Supervise factory production.", "₹3L - ₹8L", "Diploma Mech", 84, "Core,Factory", "Maintenance", "Phy", "Tools", "Realistic", "Unknown"],
  ["Junior Engineer (Elec)", "Engineering", "Maintain power systems.", "₹3L - ₹8L", "Diploma Electrical", 85, "Core,Power", "Maintenance", "Phy", "Multimeter", "Realistic", "Unknown"],
  ["Sound Engineer", "Engineering", "Mix and master audio.", "₹4L - ₹15L", "Audio Engg", 85, "Tech,Music", "Mixing", "Physics,Music", "Pro Tools", "Realistic", "Resul Pookutty"],
  ["Biomedical Engineer", "Engineering", "Design medical equipment.", "₹5L - ₹15L", "B.Tech Biomed", 88, "Med,Tech", "Device Design", "Bio,Phy", "Lab", "Investigative", "Unknown"],
  ["Marine Engineer", "Engineering", "Maintain ship engines.", "₹6L - ₹20L", "B.Tech Marine", 85, "Sea,Tech", "Engine Maint", "Phy,Math", "Ship Engine", "Realistic", "Unknown"],
  ["Environmental Engineer", "Engineering", "Develop waste/water solutions.", "₹5L - ₹15L", "B.Tech Env", 89, "Green,Tech", "Waste Mgmt", "Chem,Bio", "Lab", "Investigative", "Unknown"],
  ["Metallurgical Engineer", "Engineering", "Develop metal alloys.", "₹5L - ₹18L", "B.Tech Meta", 82, "Core,Material", "Material Sci", "Chem,Phy", "Furnace", "Investigative", "Unknown"],
  ["Ceramic Engineer", "Engineering", "Design ceramic materials.", "₹4L - ₹12L", "B.Tech Ceramic", 80, "Niche,Core", "Material Sci", "Chem", "Kiln", "Investigative", "Unknown"],
  ["Instrumentation Engineer", "Engineering", "Control industrial instruments.", "₹5L - ₹15L", "B.Tech Instru", 85, "Core,Tech", "PLC,SCADA", "Phy,Math", "Sensors", "Investigative", "Unknown"],
  ["Mechatronics Engineer", "Engineering", "Combine electronics & mechanics.", "₹6L - ₹18L", "B.Tech", 88, "Core,Tech", "Automation", "Phy,CS", "PLC", "Investigative", "Unknown"],
  ["Safety Engineer", "Engineering", "Ensure industrial safety.", "₹4L - ₹12L", "B.Tech/Diploma", 84, "Core,Safe", "Risk Assess", "Phy", "Manuals", "Conventional", "Unknown"],
  ["Production Engineer", "Engineering", "Manage manufacturing lines.", "₹4L - ₹12L", "B.Tech Prod", 83, "Core,Mgmt", "Optimization", "Phy,Math", "ERP", "Enterprising", "Unknown"],
  ["Structural Engineer", "Engineering", "Design building structures.", "₹5L - ₹15L", "M.Tech Civil", 85, "Core,Design", "Load Calc", "Phy,Math", "STAAD Pro", "Realistic", "Unknown"],
  ["Quality Control Eng", "Engineering", "Test product quality.", "₹3.5L - ₹10L", "B.Tech", 82, "Core,Test", "Testing", "Phy,Chem", "Calipers", "Conventional", "Unknown"],
  ["Solar Engineer", "Engineering", "Design solar power plants.", "₹4L - ₹12L", "B.Tech Electrical", 90, "Green,Tech", "PV Design", "Phy", "Solar Soft", "Investigative", "Unknown"],
  ["Telecom Engineer", "Engineering", "Manage 5G/4G networks.", "₹4L - ₹15L", "B.Tech ECE", 85, "Tech,Core", "Signals", "Phy,Math", "Network Tool", "Realistic", "Unknown"],
  ["Nano Technologist", "Engineering", "Work with atoms/molecules.", "₹6L - ₹20L", "M.Tech Nano", 88, "Research,Core", "Microscopy", "Phy,Chem", "Lab", "Investigative", "Unknown"],
  ["Plastic Engineer", "Engineering", "Design plastic products.", "₹3L - ₹10L", "B.Tech Polymer", 75, "Core,Mfg", "Molding", "Chem", "Molds", "Realistic", "Unknown"],
  ["Packaging Engineer", "Engineering", "Design product packaging.", "₹4L - ₹12L", "B.Tech/Diploma", 80, "Core,Design", "CAD", "Math", "CAD", "Artistic", "Unknown"],

  // --- HEALTHCARE (Doctors, Allied & Wellness) ---
  ["Doctor (MBBS)", "Healthcare", "Treat patients and save lives.", "₹10L - ₹50L+", "MBBS + MD", 95, "Medical,Respect", "Diagnosis,Empathy", "Biology,Chem", "Stethoscope", "Social", "Dr. Devi Shetty"],
  ["Nurse", "Healthcare", "Provide patient care in hospitals.", "₹3L - ₹8L", "B.Sc Nursing/GNM", 88, "Medical,Service", "Patient Care", "Biology", "Medical Kit", "Social", "Florence Nightingale"],
  ["Physiotherapist", "Healthcare", "Help rehabilitation and movement.", "₹3L - ₹12L", "BPT", 88, "Medical,Rehab", "Therapy,Anatomy", "Biology,Physics", "Therapy Equip", "Social", "Unknown"],
  ["Pharmacist", "Healthcare", "Dispense medicines and advise patients.", "₹3L - ₹10L", "B.Pharm/D.Pharm", 82, "Medical,Pharma", "Pharmacology", "Chem,Bio", "Inventory", "Conventional", "Unknown"],
  ["Clinical Psychologist", "Healthcare", "Therapy for mental health (Non-med).", "₹4L - ₹12L", "M.Phil Psychology", 88, "Medical,Mind", "CBT,Therapy", "Psychology", "Notes", "Social", "Unknown"],
  ["Ayurvedic Doctor", "Healthcare", "Treat patients using Ayurveda.", "₹4L - ₹12L", "BAMS", 82, "Medical,Alternative", "Herbal Medicine", "Biology,Sanskrit", "Herbs", "Social", "Patanjali"],
  ["Veterinary Doctor", "Healthcare", "Treat animals and pets.", "₹5L - ₹15L", "BVSc", 85, "Medical,Animals", "Animal Care", "Biology", "Vet Kit", "Realistic", "Unknown"],
  ["Dentist", "Healthcare", "Treat dental and oral health.", "₹4L - ₹15L", "BDS", 85, "Medical,Dental", "Surgery", "Biology", "Drill", "Social", "Unknown"],
  ["Nutritionist", "Healthcare", "Advise on diet and health.", "₹3L - ₹10L", "B.Sc Nutrition", 85, "Health,Lifestyle", "Diet Planning", "Bio,Chem", "Charts", "Social", "Rujuta Diwekar"],
  ["Radiology Technician", "Healthcare", "Operate X-Ray and MRI machines.", "₹3L - ₹8L", "B.Sc Radiology", 82, "Medical,Tech", "Imaging", "Physics,Bio", "MRI Machine", "Realistic", "Unknown"],
  ["Pathology Lab Tech", "Healthcare", "Test blood and samples.", "₹2.5L - ₹6L", "DMLT/BMLT", 80, "Medical,Lab", "Lab Testing", "Bio,Chem", "Microscope", "Realistic", "Unknown"],
  ["Optometrist", "Healthcare", "Examine eyes and prescribe glasses.", "₹3L - ₹8L", "B.Optom", 82, "Medical,Eye", "Eye Exam", "Physics,Bio", "Eye Chart", "Social", "Unknown"],
  ["Operation Theatre Tech", "Healthcare", "Assist in surgeries.", "₹3L - ₹7L", "Diploma OT", 84, "Medical,Tech", "Surgery Asst", "Bio", "Surgical Tools", "Realistic", "Unknown"],
  ["Dialysis Technician", "Healthcare", "Operate dialysis machines.", "₹3L - ₹6L", "Diploma Dialysis", 82, "Medical,Tech", "Dialysis", "Bio,Phy", "Dialysis M/c", "Realistic", "Unknown"],
  ["Cardiac Care Tech", "Healthcare", "Assist in heart procedures.", "₹4L - ₹9L", "B.Sc Cardiac", 85, "Medical,Tech", "ECG,Echo", "Bio", "ECG Machine", "Realistic", "Unknown"],
  ["Medical Transcriptionist", "Healthcare", "Transcribe doctor notes.", "₹2.5L - ₹5L", "Certificate", 75, "Medical,Desk", "Typing,Listening", "Bio,Eng", "Headphones", "Conventional", "Unknown"],
  ["General Duty Assistant", "Healthcare", "Assist nurses in patient care.", "₹2L - ₹4L", "Certificate (GDA)", 80, "Medical,Service", "Patient Care", "Bio", "Stretcher", "Social", "Unknown"],
  ["Yoga Therapist", "Healthcare", "Use yoga to cure ailments.", "₹3L - ₹8L", "PG Diploma Yoga", 88, "Health,Alt", "Yoga", "Bio", "Mat", "Social", "Unknown"],
  ["Naturopath", "Healthcare", "Treat using natural elements.", "₹4L - ₹10L", "BNYS", 82, "Health,Alt", "Natural Cure", "Bio", "Herbs", "Social", "Unknown"],
  ["Speech Therapist", "Healthcare", "Help with speech disorders.", "₹4L - ₹10L", "BASLP", 85, "Health,Rehab", "Speech", "Bio", "Charts", "Social", "Unknown"],
  ["Occupational Therapist", "Healthcare", "Help patients regain daily skills.", "₹4L - ₹10L", "BOT", 85, "Health,Rehab", "Motor Skills", "Bio", "Therapy Tools", "Social", "Unknown"],
  ["Hospital Administrator", "Healthcare", "Manage hospital ops.", "₹6L - ₹20L", "MHA", 88, "Health,Biz", "Management", "Bio,Biz", "Laptop", "Enterprising", "Unknown"],
  ["Home Health Aide", "Healthcare", "Care for elderly/sick at home.", "₹2L - ₹5L", "Certificate", 80, "Service,Care", "Nursing", "Bio", "Kit", "Social", "Unknown"],
  ["Dental Hygienist", "Healthcare", "Clean teeth and gums.", "₹3L - ₹6L", "Diploma", 80, "Med,Dental", "Cleaning", "Bio", "Tools", "Social", "Unknown"],
  ["Homeopathic Doctor", "Healthcare", "Homeopathy treatments.", "₹4L - ₹10L", "BHMS", 80, "Med,Alt", "Diagnosis", "Bio", "Meds", "Social", "Unknown"],
  ["Unani Doctor", "Healthcare", "Unani medicine.", "₹3L - ₹8L", "BUMS", 78, "Med,Alt", "Diagnosis", "Bio", "Herbs", "Social", "Unknown"],
  ["Anesthesia Tech", "Healthcare", "Assist anesthetist.", "₹3L - ₹7L", "Diploma/B.Sc", 82, "Med,Tech", "Assist", "Bio", "Machine", "Realistic", "Unknown"],
  ["Emergency Med Tech", "Healthcare", "Ambulance care.", "₹3L - ₹6L", "Diploma", 85, "Med,Action", "First Aid", "Bio", "Kit", "Social", "Unknown"],
  ["Phlebotomist", "Healthcare", "Draw blood samples.", "₹2L - ₹4L", "Certificate", 75, "Med,Lab", "Blood Draw", "Bio", "Syringe", "Realistic", "Unknown"],
  ["Medical Coder", "Healthcare", "Code medical records.", "₹3L - ₹6L", "Certificate", 80, "Med,Desk", "Coding", "Bio", "PC", "Conventional", "Unknown"],

  // --- FINANCE, COMMERCE & BANKING ---
  ["Chartered Accountant", "Finance", "Expert in audit, tax, and accounting.", "₹7L - ₹40L", "CA", 94, "Finance,Respect", "Accounting,Tax", "Accounts,Math", "Tally,Excel", "Conventional", "Kumar Mangalam Birla"],
  ["Investment Banker", "Finance", "Raise capital for Indian corporates.", "₹12L - ₹80L+", "MBA Finance", 95, "Finance,High Pay", "Valuation,M&A", "Finance,Math", "Excel,Bloomberg", "Enterprising", "Uday Kotak"],
  ["Bank Manager", "Finance", "Manage operations of a bank branch.", "₹8L - ₹25L", "MBA/PO Exam", 85, "Banking,Stable", "Banking,Mgmt", "Finance,Math", "Finacle", "Enterprising", "Arundhati Bhattacharya"],
  ["Stock Trader", "Finance", "Trade in BSE/NSE markets.", "₹5L - ₹50L+", "NISM Certs", 88, "Finance,Risk", "Tech Analysis", "Math,Eco", "Trading View", "Enterprising", "Rakesh Jhunjhunwala"],
  ["Company Secretary", "Finance", "Ensure corporate compliance.", "₹6L - ₹20L", "CS", 88, "Corporate,Law", "Compliance", "Law,Commerce", "Reports", "Conventional", "Unknown"],
  ["RBI Grade B Officer", "Finance", "Central bank regulator role.", "₹12L - ₹30L", "RBI Exam", 95, "Govt,Finance", "Policy,Economics", "Economics,Math", "Policy Docs", "Enterprising", "Raghuram Rajan"],
  ["SBI PO (Probationary Officer)", "Finance", "Officer in State Bank of India.", "₹8L - ₹15L", "Bank PO Exam", 90, "Govt,Banking", "Banking Ops", "Math,Reas", "Finacle", "Enterprising", "Unknown"],
  ["Actuary", "Finance", "Calculate risk for insurance.", "₹10L - ₹35L", "ACET + Papers", 92, "Math,High Pay", "Risk Stats", "Math,Stats", "Excel,R", "Investigative", "Unknown"],
  ["GST Practitioner", "Finance", "File GST returns for businesses.", "₹3L - ₹10L", "GST Exam", 85, "Tax,Freelance", "Tax Filing", "Accounts", "GST Portal", "Conventional", "Unknown"],
  ["Cost Accountant (CMA)", "Finance", "Manage cost audit and pricing.", "₹6L - ₹20L", "CMA", 88, "Finance,Cost", "Costing", "Accounts,Math", "SAP", "Conventional", "Unknown"],
  ["Bank Clerk", "Finance", "Clerical work in banks.", "₹3L - ₹6L", "IBPS Clerk", 82, "Banking,Stable", "Cash Handling", "Math", "Computer", "Conventional", "Unknown"],
  ["Insurance Agent", "Finance", "Sell insurance policies.", "Variable", "12th Pass", 80, "Sales,Freelance", "Sales", "Comm", "Policy Docs", "Enterprising", "Unknown"],
  ["Loan Officer", "Finance", "Process loan applications.", "₹3L - ₹8L", "Any Grad", 84, "Banking,Sales", "Verification", "Math", "CRM", "Conventional", "Unknown"],
  ["Mutual Fund Agent", "Finance", "Advise and sell mutual funds.", "Variable", "AMFI Cert", 85, "Sales,Finance", "Investing", "Math", "Apps", "Enterprising", "Unknown"],
  ["Stock Broker", "Finance", "Execute trades for clients.", "Variable", "NISM Cert", 85, "Finance,Sales", "Trading", "Math", "Terminal", "Enterprising", "Unknown"],
  ["Tax Consultant", "Finance", "Advise on tax planning.", "₹4L - ₹15L", "LLB/CA/B.Com", 88, "Tax,Law", "Tax Law", "Accounts", "Books", "Enterprising", "Unknown"],
  ["Internal Auditor", "Finance", "Check company accounts.", "₹5L - ₹15L", "CA/MBA", 87, "Finance,Audit", "Auditing", "Accounts", "Excel", "Conventional", "Unknown"],
  ["Forensic Accountant", "Finance", "Investigate financial crimes.", "₹6L - ₹20L", "CA/Cert", 89, "Finance,Inv", "Investigation", "Accounts", "Tools", "Investigative", "Unknown"],
  ["Research Analyst", "Finance", "Analyze stocks/sectors.", "₹6L - ₹25L", "MBA/CFA", 90, "Finance,Research", "Financial Modeling", "Math,Eco", "Excel", "Investigative", "Unknown"],
  ["Credit Manager", "Finance", "Assess creditworthiness.", "₹5L - ₹18L", "MBA/CA", 86, "Banking,Risk", "Risk Analysis", "Accounts", "Reports", "Conventional", "Unknown"],
  ["Wealth Manager", "Finance", "Manage HNI portfolios.", "₹8L - ₹30L", "MBA/CFA", 92, "Finance,Sales", "Portfolio Mgmt", "Finance", "CRM", "Enterprising", "Unknown"],
  ["Economist", "Finance", "Analyze economic trends.", "₹8L - ₹25L", "PhD Economics", 88, "Policy,Research", "Eco Analysis", "Math,Eco", "Stats", "Investigative", "Amartya Sen"],
  ["Venture Capitalist", "Finance", "Invest in startups.", "₹15L - ₹50L+", "MBA", 95, "Finance,High Pay", "Investment", "Biz", "Network", "Enterprising", "Unknown"],
  ["Accountant", "Finance", "Maintain daily accounts.", "₹3L - ₹8L", "B.Com", 80, "Finance,Stable", "Bookkeeping", "Accounts", "Tally", "Conventional", "Unknown"],
  ["Payroll Specialist", "Finance", "Process employee salaries.", "₹3L - ₹7L", "B.Com", 80, "HR,Finance", "Payroll", "Accounts", "Excel", "Conventional", "Unknown"],

  // --- GOVERNMENT SERVICES (UPSC, SSC, Railways) ---
  ["IAS Officer", "Govt", "District administration and policy making.", "₹56k - ₹2.5L/mo", "UPSC CSE", 99, "Govt,Power", "Admin,Policy", "GenStudies", "Files", "Enterprising", "Tina Dabi"],
  ["IPS Officer", "Govt", "Police leadership and law enforcement.", "₹56k - ₹2.25L/mo", "UPSC CSE", 99, "Govt,Power", "Law Order", "GenStudies", "Uniform", "Enterprising", "Kiran Bedi"],
  ["IFS Officer", "Govt", "Represent India in foreign countries.", "₹60k - ₹2.4L/mo", "UPSC CSE", 98, "Govt,Foreign", "Diplomacy", "Intl Relations", "Documents", "Artistic", "S Jaishankar"],
  ["IRS Officer", "Govt", "Collect Direct/Indirect Taxes (Income Tax/GST).", "₹56k - ₹2.25L/mo", "UPSC CSE", 97, "Govt,Finance", "Taxation", "Finance,Law", "Tax Portal", "Conventional", "Unknown"],
  ["SSC CGL Officer", "Govt", "Inspector in Income Tax/CBI/Excise.", "₹45k - ₹80k/mo", "SSC CGL", 92, "Govt,Stable", "Inspection", "Math,Eng", "Files", "Conventional", "Unknown"],
  ["Railway Station Master", "Govt", "Manage train station operations.", "₹40k - ₹80k/mo", "RRB NTPC", 88, "Railways,Ops", "Management", "Math,Reas", "Control Panel", "Enterprising", "Unknown"],
  ["Loco Pilot (Train Driver)", "Govt", "Drive Indian Railways trains.", "₹30k - ₹1L/mo", "RRB ALP + ITI", 88, "Railways,Tech", "Driving", "Tech", "Train Engine", "Realistic", "Unknown"],
  ["Railway Group D", "Govt", "Track maintenance and support.", "₹25k - ₹40k/mo", "RRC Group D", 80, "Railways,Stable", "Maintenance", "Physical", "Tools", "Realistic", "Unknown"],
  ["SSC CHSL (LDC/DEO)", "Govt", "Clerical work in central ministries.", "₹25k - ₹45k/mo", "SSC CHSL", 85, "Govt,Desk", "Typing,Filing", "English", "Computer", "Conventional", "Unknown"],
  ["Anganwadi Worker", "Govt", "Rural child and mother care.", "₹5k - ₹10k/mo", "10th Pass", 70, "Govt,Social", "Care", "Local Lang", "Register", "Social", "Unknown"],
  ["Gram Sevak/Panchayat Sec", "Govt", "Village level administration.", "₹20k - ₹40k/mo", "State Exam", 82, "Govt,Rural", "Admin", "Local Lang", "Register", "Social", "Unknown"],
  ["Patwari / Lekhpal", "Govt", "Maintain land records in villages.", "₹25k - ₹40k/mo", "State Exam", 85, "Govt,Land", "Land Measure", "Math", "Maps", "Conventional", "Unknown"],
  ["State PSC Officer (SDM/DySP)", "Govt", "State level administration.", "₹50k - ₹1.5L/mo", "State PSC", 95, "Govt,Power", "Admin", "GenStudies", "Files", "Enterprising", "Unknown"],
  ["Tehsildar", "Govt", "Revenue officer at Tehsil level.", "₹40k - ₹80k/mo", "State Exam", 88, "Govt,Admin", "Revenue", "Law", "Files", "Conventional", "Unknown"],
  ["Forest Ranger", "Govt", "Protect forests and wildlife.", "₹35k - ₹70k/mo", "State/UPSC", 88, "Govt,Nature", "Patrol", "Bio,Env", "Jeep", "Realistic", "Unknown"],
  ["SSC MTS", "Govt", "Multi-tasking staff in ministries.", "₹20k - ₹30k/mo", "SSC MTS", 80, "Govt,Entry", "Office Asst", "GenStudies", "Files", "Conventional", "Unknown"],
  ["Intelligence Bureau Officer", "Govt", "Internal intelligence gathering.", "₹45k - ₹1L/mo", "IB ACIO", 92, "Govt,Spy", "Intel", "Reas,Eng", "Classified", "Investigative", "Unknown"],
  ["CBI Sub-Inspector", "Govt", "Investigate major crimes.", "₹50k - ₹90k/mo", "SSC CGL", 93, "Govt,Police", "Investigation", "Law", "Files", "Investigative", "Unknown"],
  ["Food Inspector", "Govt", "Check food safety standards.", "₹35k - ₹70k/mo", "State/Central", 85, "Govt,Health", "Inspection", "Bio,Chem", "Kit", "Investigative", "Unknown"],
  ["Postal Assistant", "Govt", "Work in Post Offices.", "₹25k - ₹45k/mo", "SSC CHSL", 82, "Govt,Service", "Mail Ops", "Math", "Computer", "Conventional", "Unknown"],
  ["KVS Teacher", "Govt", "Teach in Kendriya Vidyalayas.", "₹45k - ₹80k/mo", "CTET + KVS", 90, "Govt,Teaching", "Teaching", "Subject", "Board", "Social", "Unknown"],
  ["Junior Hindi Translator", "Govt", "Translate docs in ministries.", "₹35k - ₹70k/mo", "SSC JHT", 85, "Govt,Lang", "Translation", "Hindi,Eng", "PC", "Artistic", "Unknown"],
  ["Drug Inspector", "Govt", "Inspect pharma companies.", "₹45k - ₹90k/mo", "B.Pharm + Exam", 90, "Govt,Pharma", "Inspection", "Pharma", "Files", "Investigative", "Unknown"],
  ["Customs Examiner", "Govt", "Check cargo at ports/airports.", "₹50k - ₹90k/mo", "SSC CGL", 92, "Govt,Port", "Checking", "Law", "Scanner", "Conventional", "Unknown"],
  ["ASO in MEA", "Govt", "Asst Section Officer in Foreign Ministry.", "₹50k - ₹1.5L (Foreign)", "SSC CGL", 95, "Govt,Foreign", "Admin", "English", "Files", "Conventional", "Unknown"],
  ["ISRO Scientist", "Govt", "Space research.", "₹60k - ₹1.5L/mo", "ISRO Exam", 96, "Govt,Space", "R&D", "Phy,Math", "Lab", "Investigative", "Unknown"],
  ["DRDO Scientist", "Govt", "Defense research.", "₹60k - ₹1.5L/mo", "GATE/Exam", 96, "Govt,Defense", "R&D", "Phy,Math", "Lab", "Investigative", "APJ Abdul Kalam"],
  ["RBI Assistant", "Govt", "Clerical/Asst role in RBI.", "₹35k - ₹60k/mo", "RBI Asst", 88, "Govt,Bank", "Banking", "Math", "PC", "Conventional", "Unknown"],
  ["NABARD Officer", "Govt", "Rural bank development.", "₹60k - ₹1.2L/mo", "NABARD Exam", 92, "Govt,Rural", "Rural Dev", "Agri,Eco", "Files", "Enterprising", "Unknown"],
  ["FCI Manager", "Govt", "Manage food grain storage.", "₹40k - ₹80k/mo", "FCI Exam", 85, "Govt,Ops", "Logistics", "Mgmt", "Depot", "Enterprising", "Unknown"],

  // --- DEFENSE & PARAMILITARY ---
  ["Army Officer (NDA/CDS)", "Defense", "Lead troops in Indian Army.", "₹56k - ₹2.5L/mo", "NDA/CDS", 96, "Defense,Leader", "Combat,Leadership", "Math,Phy", "Weapons", "Enterprising", "Sam Manekshaw"],
  ["Air Force Pilot", "Defense", "Fly fighter jets like Rafale/Tejas.", "₹80k - ₹3L/mo", "NDA/AFCAT", 96, "Defense,Pilot", "Flying", "Phy,Math", "Jet", "Realistic", "Abhinandan Varthaman"],
  ["Navy Officer", "Defense", "Command ships and submarines.", "₹56k - ₹2.5L/mo", "NDA/CDS", 95, "Defense,Sea", "Navigation", "Math,Phy", "Ship", "Enterprising", "Unknown"],
  ["Agniveer (General Duty)", "Defense", "Soldier in Army (4 year tour).", "₹30k - ₹40k/mo", "Agnipath Rally", 85, "Defense,Action", "Combat", "Physical", "Rifle", "Realistic", "Unknown"],
  ["Paramilitary (BSF/CRPF)", "Defense", "Border security and internal riot control.", "₹30k - ₹60k/mo", "SSC GD Constable", 88, "Defense,Action", "Patrol", "Physical", "Rifle", "Realistic", "Unknown"],
  ["Police Constable", "Defense", "Maintain law and order in state.", "₹25k - ₹45k/mo", "State Police Exam", 85, "Defense,Police", "Patrol", "Physical", "Lathi", "Realistic", "Unknown"],
  ["Police Sub-Inspector", "Defense", "Investigate crimes at station level.", "₹35k - ₹60k/mo", "SI Exam", 90, "Defense,Police", "Investigation", "Law", "Pistol", "Enterprising", "Unknown"],
  ["Commando (NSG/MARCOS)", "Defense", "Special forces operations.", "₹60k - ₹1.5L/mo", "Internal Selection", 98, "Defense,Elite", "Ops", "Physical", "Weapons", "Realistic", "Unknown"],
  ["Coast Guard Officer", "Defense", "Protect coastal borders.", "₹56k - ₹1.5L/mo", "ICG Exam", 92, "Defense,Sea", "Patrol", "Math,Phy", "Ship", "Enterprising", "Unknown"],
  ["Assam Rifles Rifleman", "Defense", "Guard North East borders.", "₹30k - ₹50k/mo", "Rally", 85, "Defense,Action", "Patrol", "Physical", "Rifle", "Realistic", "Unknown"],

  // --- VOCATIONAL & ITI (Skilled Trades) ---
  ["Electrician", "Vocational", "Install and repair wiring.", "₹15k - ₹40k/mo", "ITI Electrician", 85, "Trade,Fix", "Wiring", "Phy", "Pliers", "Realistic", "Unknown"],
  ["Fitter", "Vocational", "Assemble machine parts in factories.", "₹15k - ₹35k/mo", "ITI Fitter", 82, "Trade,Factory", "Assembly", "Phy", "Tools", "Realistic", "Unknown"],
  ["Welder", "Vocational", "Weld metal structures.", "₹15k - ₹45k/mo", "ITI Welder", 80, "Trade,Fix", "Welding", "Phy", "Torch", "Realistic", "Unknown"],
  ["Plumber", "Vocational", "Install pipes and water systems.", "₹15k - ₹40k/mo", "ITI Plumber", 82, "Trade,Fix", "Pipe Fitting", "Phy", "Wrench", "Realistic", "Unknown"],
  ["Carpenter", "Vocational", "Make furniture and wood structures.", "₹15k - ₹40k/mo", "ITI Carpenter", 80, "Trade,Creative", "Woodwork", "Math", "Saw", "Realistic", "Unknown"],
  ["Mechanic (Diesel/Motor)", "Vocational", "Repair vehicles and engines.", "₹15k - ₹35k/mo", "ITI Mechanic", 85, "Trade,Auto", "Repair", "Phy", "Wrench", "Realistic", "Unknown"],
  ["AC & Fridge Mechanic", "Vocational", "Repair HVAC systems.", "₹18k - ₹45k/mo", "ITI MRAC", 88, "Trade,Demand", "Cooling Systems", "Phy", "Gauge", "Realistic", "Unknown"],
  ["Draftsman (Civil/Mech)", "Vocational", "Draw technical plans.", "₹18k - ₹35k/mo", "ITI Draftsman", 84, "Trade,Desk", "AutoCAD", "Math", "PC", "Conventional", "Unknown"],
  ["Surveyor", "Vocational", "Measure land for construction.", "₹18k - ₹35k/mo", "ITI Surveyor", 82, "Trade,Field", "Surveying", "Math", "Theodolite", "Realistic", "Unknown"],
  ["Machinist", "Vocational", "Operate lathe/CNC machines.", "₹15k - ₹35k/mo", "ITI Machinist", 82, "Trade,Factory", "Machining", "Phy", "Lathe", "Realistic", "Unknown"],
  ["Turner", "Vocational", "Operate turning machines.", "₹15k - ₹30k/mo", "ITI Turner", 80, "Trade,Factory", "Turning", "Phy", "Lathe", "Realistic", "Unknown"],
  ["Wireman", "Vocational", "Wiring for buildings.", "₹12k - ₹30k/mo", "ITI Wireman", 80, "Trade,Fix", "Wiring", "Phy", "Tools", "Realistic", "Unknown"],
  ["Electronic Mechanic", "Vocational", "Repair PCBs and gadgets.", "₹15k - ₹35k/mo", "ITI Electronic", 85, "Trade,Tech", "Soldering", "Phy", "Multimeter", "Realistic", "Unknown"],
  ["COPA (Computer Operator)", "Vocational", "Office data entry assistant.", "₹12k - ₹25k/mo", "ITI COPA", 75, "Trade,Desk", "Data Entry", "Computer", "PC", "Conventional", "Unknown"],
  ["Stenographer", "Vocational", "Type shorthand for courts/offices.", "₹20k - ₹45k/mo", "ITI/Polytechnic", 82, "Trade,Office", "Shorthand", "Lang", "Typewriter", "Conventional", "Unknown"],
  ["Beautician / Makeup Artist", "Vocational", "Styling and makeup services.", "₹15k - ₹1L/mo", "Diploma Beauty", 88, "Creative,Self", "Makeup", "Art", "Kit", "Artistic", "Unknown"],
  ["Fashion Designer (Diploma)", "Vocational", "Design clothes.", "₹15k - ₹50k/mo", "Diploma Fashion", 85, "Creative,Design", "Sewing", "Art", "Machine", "Artistic", "Unknown"],
  ["Tailor / Dressmaker", "Vocational", "Stitch garments.", "₹10k - ₹30k/mo", "ITI Dressmaking", 80, "Trade,Creative", "Stitching", "Art", "Machine", "Realistic", "Unknown"],
  ["Baker / Confectioner", "Vocational", "Bake cakes and breads.", "₹15k - ₹40k/mo", "ITI/Diploma", 85, "Trade,Food", "Baking", "Bio", "Oven", "Realistic", "Unknown"],
  ["Hotel Management Diploma", "Vocational", "Service in hotels.", "₹15k - ₹35k/mo", "Diploma HM", 82, "Trade,Service", "Hospitality", "Comm", "Tray", "Social", "Unknown"],
  ["Fire & Safety Officer", "Vocational", "Manage fire safety.", "₹20k - ₹50k/mo", "Diploma Safety", 85, "Trade,Safety", "Fire Fighting", "Phy", "Extinguisher", "Realistic", "Unknown"],
  ["Lab Technician (School)", "Vocational", "Maintain school labs.", "₹15k - ₹30k/mo", "B.Sc/Diploma", 75, "Edu,Lab", "Lab Maint", "Sci", "Apparatus", "Realistic", "Unknown"],
  ["Library Assistant", "Vocational", "Manage library books.", "₹15k - ₹30k/mo", "B.Lib/Diploma", 75, "Edu,Desk", "Cataloging", "Lang", "Books", "Conventional", "Unknown"],
  ["Yoga Instructor", "Vocational", "Teach yoga.", "₹15k - ₹50k/mo", "Certificate", 85, "Health,Self", "Yoga", "Phy", "Mat", "Social", "Ramdev"],
  ["Gym Trainer", "Vocational", "Personal fitness training.", "₹15k - ₹50k/mo", "Certificate", 85, "Health,Active", "Training", "Bio", "Weights", "Social", "Unknown"],
  ["Driver (Heavy Vehicle)", "Vocational", "Drive buses/trucks.", "₹15k - ₹35k/mo", "License", 75, "Trade,Travel", "Driving", "Phy", "Bus", "Realistic", "Unknown"],
  ["Crane Operator", "Vocational", "Operate cranes in construction.", "₹20k - ₹50k/mo", "License", 80, "Trade,Site", "Ops", "Phy", "Crane", "Realistic", "Unknown"],
  ["CNC Operator", "Vocational", "Operate CNC machines.", "₹15k - ₹30k/mo", "ITI", 82, "Trade,Tech", "CNC Ops", "Math", "CNC", "Realistic", "Unknown"],
  ["Mobile Repair Tech", "Vocational", "Fix mobile phones.", "₹15k - ₹40k/mo", "Certificate", 85, "Trade,Tech", "Repair", "Phy", "Tools", "Realistic", "Unknown"],
  ["CCTV Technician", "Vocational", "Install security cameras.", "₹15k - ₹35k/mo", "Certificate", 82, "Trade,Tech", "Install", "Phy", "Drill", "Realistic", "Unknown"],

  // --- MEDIA, CREATIVE & ENTERTAINMENT ---
  ["YouTuber / Content Creator", "Creative", "Make videos for YouTube/Insta.", "Variable", "Creativity", 90, "NewAge,Fame", "Video Edit,Acting", "Art", "Camera", "Artistic", "CarryMinati"],
  ["Video Editor", "Creative", "Edit videos for films/social.", "₹3L - ₹12L", "Certificate/Deg", 88, "Creative,Tech", "Premiere Pro", "Art", "PC", "Artistic", "Unknown"],
  ["Graphic Designer", "Creative", "Create visuals for brands.", "₹3L - ₹10L", "B.Des/Diploma", 85, "Creative,Tech", "Photoshop", "Art", "Tablet", "Artistic", "Unknown"],
  ["Journalist / Anchor", "Creative", "Report news on TV/Print.", "₹3L - ₹15L", "BJMC", 85, "Media,Public", "Reporting", "Lang", "Mic", "Artistic", "Arnab Goswami"],
  ["Copywriter", "Creative", "Write ads and marketing text.", "₹3L - ₹10L", "BA English", 82, "Media,Writing", "Writing", "Lang", "PC", "Artistic", "Prasoon Joshi"],
  ["Digital Marketer", "Creative", "Market brands online.", "₹4L - ₹12L", "Any Grad", 92, "Tech,Biz", "Ads,SEO", "Biz", "Analytics", "Enterprising", "Unknown"],
  ["Fashion Designer", "Creative", "Design clothing lines.", "₹4L - ₹20L", "B.Des (NIFT)", 85, "Design,Glamour", "Sketching", "Art", "Fabric", "Artistic", "Manish Malhotra"],
  ["Interior Designer", "Creative", "Design home/office spaces.", "₹3L - ₹15L", "B.Des/Diploma", 85, "Design,Space", "CAD,Decor", "Art,Math", "AutoCAD", "Artistic", "Gauri Khan"],
  ["Animator", "Creative", "Create 2D/3D animation.", "₹4L - ₹15L", "B.Des/Diploma", 88, "Tech,Art", "Blender,Maya", "Art,Math", "PC", "Artistic", "Unknown"],
  ["VFX Artist", "Creative", "Create visual effects for movies.", "₹4L - ₹18L", "Diploma VFX", 90, "Tech,Movie", "Compositing", "Art", "Nuke", "Artistic", "Unknown"],
  ["Sound Designer", "Creative", "Create sound effects.", "₹3L - ₹12L", "Audio Diploma", 80, "Tech,Music", "Mixing", "Music", "DAW", "Artistic", "Unknown"],
  ["RJ (Radio Jockey)", "Creative", "Host radio shows.", "₹3L - ₹10L", "Any Grad", 80, "Media,Voice", "Speaking", "Lang", "Mic", "Artistic", "Unknown"],
  ["Event Manager", "Creative", "Plan weddings/events.", "₹3L - ₹15L", "BBA/Diploma", 85, "Biz,Org", "Planning", "Comm", "Phone", "Enterprising", "Unknown"],
  ["Wedding Photographer", "Creative", "Shoot weddings.", "₹3L - ₹20L", "Skill", 85, "Art,Biz", "Photography", "Art", "Camera", "Artistic", "Unknown"],
  ["Product Designer", "Creative", "Design physical products.", "₹6L - ₹20L", "B.Des", 90, "Design,Tech", "Prototyping", "Phys,Art", "3D Print", "Artistic", "Unknown"],
  ["Film Director", "Creative", "Direct movies.", "Variable", "Film School", 85, "Movie,Leader", "Storytelling", "Art", "Set", "Artistic", "Rajkumar Hirani"],
  ["Actor", "Creative", "Act in movies/TV.", "Variable", "Talent", 85, "Fame,Risk", "Acting", "Art", "Script", "Artistic", "Shah Rukh Khan"],
  ["Voice Over Artist", "Creative", "Voice for ads/cartoons.", "Variable", "Talent", 80, "Voice,Freelance", "Voice Mod", "Lang", "Mic", "Artistic", "Unknown"],
  ["Art Director", "Creative", "Manage visual style.", "₹5L - ₹20L", "BFA", 85, "Art,Mgmt", "Visuals", "Art", "Studio", "Artistic", "Unknown"],
  ["Public Relations (PR)", "Creative", "Manage brand image.", "₹4L - ₹15L", "MBA/PGDM", 85, "Biz,Comm", "Networking", "Lang", "Phone", "Enterprising", "Unknown"],
  
  // --- LAW, HUMANITIES & SOCIAL ---
  ["Lawyer (Advocate)", "Legal", "Argue cases in court.", "₹3L - ₹50L+", "LLB", 90, "Law,Argument", "Argument,Drafting", "PolSci", "Constitution", "Enterprising", "Harish Salve"],
  ["Judge", "Legal", "Give verdicts in court.", "₹1L - ₹2.5L/mo", "Judicial Exam", 95, "Law,Respect", "Judgment", "Law", "Gavel", "Investigative", "CJI DY Chandrachud"],
  ["Corporate Lawyer", "Legal", "Handle company legal matters.", "₹6L - ₹30L", "LLB (NLU)", 92, "Law,Corp", "Contracts", "Law", "Laptop", "Enterprising", "Unknown"],
  ["Professor", "Education", "Teach in college/university.", "₹6L - ₹20L", "PhD/NET", 88, "Edu,Respect", "Research,Teaching", "Subject", "Books", "Social", "Unknown"],
  ["School Teacher", "Education", "Teach in schools.", "₹3L - ₹10L", "B.Ed/D.El.Ed", 85, "Edu,Stable", "Teaching", "Subject", "Board", "Social", "Unknown"],
  ["Social Worker", "Social", "Help NGOs and communities.", "₹2L - ₹8L", "MSW", 80, "Social,Help", "Empathy", "Soc", "Field", "Social", "Sudha Murty"],
  ["Journalist (Print)", "Media", "Write for newspapers.", "₹3L - ₹10L", "BJMC", 80, "Media,Write", "Reporting", "Lang", "Pad", "Artistic", "Unknown"],
  ["Translator", "Lang", "Translate books/docs.", "₹3L - ₹10L", "MA Language", 82, "Lang,Desk", "Trans", "Lang", "PC", "Artistic", "Unknown"],
  ["Historian", "Humanities", "Study history.", "₹4L - ₹12L", "PhD History", 75, "Research,Acad", "Research", "Hist", "Archives", "Investigative", "Romila Thapar"],
  ["Archaeologist", "Humanities", "Excavate ancient sites.", "₹4L - ₹10L", "MA Arch", 75, "Field,Hist", "Excavation", "Hist", "Brush", "Investigative", "Unknown"],
  ["Political Analyst", "Humanities", "Analyze politics.", "₹5L - ₹20L", "Pol Sci", 85, "Media,Pol", "Analysis", "PolSci", "TV", "Investigative", "Prashant Kishor"],
  ["Librarian", "Education", "Manage libraries.", "₹3L - ₹10L", "B.Lib", 75, "Edu,Quiet", "Org", "Lang", "Books", "Conventional", "Unknown"],
  ["Counselor", "Social", "Career/School counseling.", "₹3L - ₹8L", "MA Psych", 85, "Social,Help", "Listening", "Psych", "Notes", "Social", "Unknown"],
  ["HR Manager", "Business", "Manage employees.", "₹5L - ₹20L", "MBA HR", 88, "Corp,Ppl", "Hiring", "Psych", "Excel", "Social", "Unknown"],
  ["Think Tank Researcher", "Humanities", "Policy research.", "₹6L - ₹20L", "Masters", 85, "Policy,Res", "Writing", "PolSci", "PC", "Investigative", "Unknown"],

  // --- AGRICULTURE & RURAL ---
  ["Agricultural Scientist", "Agriculture", "Improve crops and farming.", "₹6L - ₹15L", "B.Sc/M.Sc Agri", 90, "Agri,Tech", "R&D", "Bio", "Lab", "Investigative", "MS Swaminathan"],
  ["Horticulturist", "Agriculture", "Grow fruits/flowers.", "₹3L - ₹10L", "B.Sc Hort", 85, "Agri,Nature", "Planting", "Bio", "Field", "Realistic", "Unknown"],
  ["Dairy Farmer", "Agriculture", "Manage milk production.", "Variable", "Skill/Degree", 85, "Agri,Biz", "Animal Care", "Bio", "Farm", "Enterprising", "Verghese Kurien"],
  ["Fisheries Officer", "Agriculture", "Manage fish farming.", "₹4L - ₹10L", "B.F.Sc", 82, "Agri,Govt", "Aquaculture", "Bio", "Net", "Realistic", "Unknown"],
  ["Forestry Officer", "Agriculture", "Manage forests.", "₹5L - ₹12L", "B.Sc Forestry", 85, "Nature,Govt", "Conservation", "Bio", "Jeep", "Realistic", "Unknown"],
  ["Organic Farmer", "Agriculture", "Eco-friendly farming.", "Variable", "Skill", 88, "Agri,Biz", "Farming", "Bio", "Farm", "Enterprising", "Unknown"],
  ["Agri-Business Manager", "Agriculture", "Manage farm businesses.", "₹5L - ₹15L", "MBA Agri", 90, "Agri,Corp", "Sales", "Biz", "PC", "Enterprising", "Unknown"],
  ["Food Technologist", "Agriculture", "Process food products.", "₹4L - ₹12L", "B.Tech Food", 85, "Agri,Factory", "Processing", "Chem", "Lab", "Investigative", "Unknown"],
  ["Veterinary Assistant", "Agriculture", "Help vet doctors.", "₹2L - ₹5L", "Diploma", 80, "Animal,Help", "Care", "Bio", "Kit", "Realistic", "Unknown"],
  ["Tea Taster", "Agriculture", "Taste and grade tea.", "₹5L - ₹20L", "Skill", 82, "Niche,Food", "Tasting", "Bio", "Cup", "Artistic", "Unknown"],

  // --- LOGISTICS, AVIATION & MERCHANT NAVY ---
  ["Commercial Pilot", "Aviation", "Fly passenger planes (IndiGo/Air India).", "₹1.5L - ₹5L/mo", "CPL License", 95, "HighPay,Travel", "Flying", "Phy,Math", "Plane", "Realistic", "Unknown"],
  ["Cabin Crew / Air Hostess", "Aviation", "Passenger service on flights.", "₹30k - ₹1L/mo", "12th/Diploma", 85, "Travel,Service", "Service", "Comm", "Uniform", "Social", "Unknown"],
  ["Merchant Navy Officer", "Logistics", "Work on cargo ships.", "₹1L - ₹5L/mo", "B.Sc Nautical", 95, "Sea,HighPay", "Navigation", "Phy,Math", "Ship", "Realistic", "Unknown"],
  ["Air Traffic Controller", "Aviation", "Manage flight paths.", "₹60k - ₹1.5L/mo", "Exam", 92, "Avia,Stress", "Control", "Phy,Math", "Radar", "Conventional", "Unknown"],
  ["Airport Manager", "Aviation", "Manage airport ops.", "₹50k - ₹1.5L/mo", "MBA Avia", 88, "Avia,Mgmt", "Ops", "Biz", "Radio", "Enterprising", "Unknown"],
  ["Supply Chain Manager", "Logistics", "Manage goods movement.", "₹6L - ₹20L", "MBA Ops", 90, "Corp,Ops", "Logistics", "Math", "Excel", "Enterprising", "Unknown"],
  ["Truck Driver (Heavy)", "Logistics", "Transport goods.", "₹20k - ₹40k/mo", "License", 75, "Travel,Hard", "Driving", "Phy", "Truck", "Realistic", "Unknown"],
  ["Warehouse Manager", "Logistics", "Manage godowns.", "₹3L - ₹8L", "Grad", 80, "Ops,Store", "Inventory", "Math", "Scanner", "Conventional", "Unknown"],
  ["Customs Agent", "Logistics", "Clear import/export.", "₹3L - ₹10L", "License", 82, "Biz,Law", "Docs", "Law", "PC", "Conventional", "Unknown"],
  ["Drone Logistics Pilot", "Logistics", "Deliver via drone.", "₹20k - ₹50k/mo", "License", 90, "Tech,New", "Drone Ops", "Tech", "Remote", "Realistic", "Unknown"],

  // --- SPORTS & FITNESS ---
  ["Cricketer", "Sports", "Professional player.", "Variable", "Talent", 90, "Fame,Sport", "Cricket", "Phy", "Bat", "Realistic", "Virat Kohli"],
  ["Sports Coach", "Sports", "Train athletes.", "₹3L - ₹15L", "Diploma Sports", 85, "Sport,Teach", "Training", "Phy", "Whistle", "Social", "Pullela Gopichand"],
  ["Sports Physiotherapist", "Sports", "Treat player injuries.", "₹5L - ₹20L", "MPT Sports", 88, "Med,Sport", "Rehab", "Bio", "Table", "Social", "Unknown"],
  ["Sports Journalist", "Media", "Cover sports news.", "₹4L - ₹12L", "BJMC", 85, "Media,Sport", "Reporting", "Lang", "Mic", "Artistic", "Harsha Bhogle"],
  ["Umpire / Referee", "Sports", "Officiate matches.", "Variable", "Cert", 80, "Sport,Rule", "Rules", "Phy", "Card", "Conventional", "Unknown"],
  ["Yoga Teacher", "Sports", "Teach yoga.", "₹20k - ₹1L/mo", "Cert", 88, "Health,Zen", "Yoga", "Phy", "Mat", "Social", "Unknown"],
  ["Personal Trainer", "Sports", "Gym training.", "₹20k - ₹1L/mo", "Cert", 85, "Fit,Biz", "Gym", "Bio", "Weights", "Social", "Unknown"],
  ["Sports Manager", "Sports", "Manage leagues/players.", "₹5L - ₹20L", "MBA Sports", 88, "Biz,Sport", "Mgmt", "Biz", "PC", "Enterprising", "Unknown"],
  ["E-Sports Player", "Sports", "Pro gamer.", "Variable", "Skill", 90, "New,Tech", "Gaming", "Reflex", "PC", "Realistic", "Mortal"],
  ["Nutritionist (Sports)", "Sports", "Diet for athletes.", "₹4L - ₹15L", "M.Sc", 85, "Health,Sport", "Diet", "Bio", "Chart", "Investigative", "Unknown"]
];

// --- HYDRATE INTO OBJECTS ---
export const MOCK_CAREERS: Career[] = CAREER_RAW_DATA.map((data, index) => ({
  id: generateId('CAR', index),
  title: data[0] as string,
  industry: data[1] as string,
  description: data[2] as string,
  salaryRange: data[3] as string,
  education: data[4] as string,
  growthScore: data[5] as number,
  tags: (data[6] as string).split(','),
  skills: (data[7] as string).split(','),
  subjects: (data[8] as string).split(','),
  tools: (data[9] as string).split(','),
  personalityType: data[10] as string,
  famousPeople: (data[11] as string) !== "Unknown" ? [(data[11] as string)] : [],
  // Improved image source logic based on request
  imageUrl: `https://source.unsplash.com/800x600/?${encodeURIComponent(data[0] as string)},${encodeURIComponent(data[1] as string)}`
}));

export const MOCK_SCHOLARSHIPS: Scholarship[] = [
  { id: 'SCH001', name: 'PM Yasasvi Scholarship', category: 'Central', country: 'India', amount: '₹75,000 - ₹1.25 Lakh/yr', deadline: 'Aug 2025', eligibility: 'OBC/EBC/DNT Students, Class 9-12', link: 'https://yet.nta.ac.in/' },
  { id: 'SCH002', name: 'National Means-cum-Merit (NMMS)', category: 'Central', country: 'India', amount: '₹12,000/yr', deadline: 'Nov 2025', eligibility: 'Class 8 students, Income < 3.5L', link: 'https://scholarships.gov.in/' },
  { id: 'SCH003', name: 'KVPY (Kishore Vaigyanik Protsahan Yojana)', category: 'Exam', country: 'India', amount: '₹5,000 - ₹7,000/mo', deadline: 'Sep 2025', eligibility: 'Class 11, 12, UG Science', link: 'http://www.kvpy.iisc.ernet.in/' },
  { id: 'SCH004', name: 'Tata Trusts Scholarship', category: 'Private', country: 'India', amount: 'Variable', deadline: 'Jan 2026', eligibility: 'UG/PG Medical & Engg', link: 'https://www.tatatrusts.org/' },
  { id: 'SCH005', name: 'Reliance Foundation Scholarship', category: 'Private', country: 'India', amount: '₹2 Lakh - ₹6 Lakh', deadline: 'Oct 2025', eligibility: 'UG/PG Top Students', link: 'https://www.reliancefoundation.org/' },
  { id: 'SCH006', name: 'UP Scholarship (Post Matric)', category: 'State', country: 'India', amount: 'Tuition Refund', deadline: 'Dec 2025', eligibility: 'UP Domicile Students', link: 'https://scholarship.up.gov.in/' },
  { id: 'SCH007', name: 'Inspire SHE Scholarship', category: 'Central', country: 'India', amount: '₹80,000/yr', deadline: 'Dec 2025', eligibility: 'Top 1% in Class 12 Boards', link: 'https://online-inspire.gov.in/' },
  { id: 'SCH008', name: 'HDFC Badte Kadam', category: 'Private', country: 'India', amount: '₹30,000 - ₹1 Lakh', deadline: 'Sep 2025', eligibility: 'Class 11 to UG', link: 'https://www.hdfcbank.com/' },
  { id: 'SCH009', name: 'NTSE (National Talent Search)', category: 'Exam', country: 'India', amount: '₹1,250 - ₹2,000/mo', deadline: 'Closed', eligibility: 'Class 10 Students', link: 'https://ncert.nic.in/' },
  { id: 'SCH010', name: 'AICTE Pragati (For Girls)', category: 'Central', country: 'India', amount: '₹50,000/yr', deadline: 'Oct 2025', eligibility: 'Girls in Tech Diploma/Degree', link: 'https://www.aicte-india.org/' },
  { id: 'SCH011', name: 'ONGC Scholarship', category: 'Private', country: 'India', amount: '₹48,000/yr', deadline: 'Aug 2025', eligibility: 'SC/ST/OBC in Engg/MBBS', link: 'https://ongcindia.com/' },
  { id: 'SCH012', name: 'Swami Vivekananda Merit (WB)', category: 'State', country: 'India', amount: '₹1,000 - ₹5,000/mo', deadline: 'Nov 2025', eligibility: 'West Bengal Students', link: 'https://svmcm.wbhed.gov.in/' },
  { id: 'SCH013', name: 'MahaDBT (Maharashtra)', category: 'State', country: 'India', amount: 'Variable', deadline: 'Mar 2026', eligibility: 'Maharashtra Students', link: 'https://mahadbtmahait.gov.in/' },
  { id: 'SCH014', name: 'Vidyadhan Scholarship', category: 'Private', country: 'India', amount: '₹6,000 - ₹60,000/yr', deadline: 'Jun 2025', eligibility: 'Class 10 Pass (South India)', link: 'https://www.vidyadhan.org/' },
  { id: 'SCH015', name: 'Post-Matric SC/ST', category: 'Central', country: 'India', amount: 'Variable', deadline: 'Ongoing', eligibility: 'SC/ST Students', link: 'https://scholarships.gov.in/' }
];
